### ISSUE TITLE
Argument treated as operator in custom function.

### ISSUE THREAD

**Issue by sourav3-sharechat** [jwadhams/json-logic-js#87]
```
const { JsonLogicUtil } = loadClass('utils');
let rules = {
    or: [
        {
            and: [
                {
                    doesUserAppInclusionOrExclusionMatches: [
                        {
                            var: 'userAppList',
                        },
                        {
                                segmentAppInclusion: [
                                    1,
                                ],
                        },
                    ],
                },
            ],
        },
        {
            and: [
                {
                    doesUserAppInclusionOrExclusionMatches: [
                        {
                            var: 'userAppList',
                        },
                        {
                            //segmentAppExclusion: [
                            //     4,
                            // ],
                        },
                    ],
                },
            ],
        },
    ],
};
const userAttribute = {
    userId: '123456789',
    userAppList: [ 1 ],
};
try {
    JsonLogicUtil.apply(rules, userAttribute);
} catch (e) {
    console.log(e);
}
```

------- In JsonLogicUtil -------------
```
const doesUserAppInclusionOrExclusionMatches = (appList, appIncExclObj) => {
    const { segmentAppInclusion, segmentAppExclusion } = appIncExclObj;
    if (!ObjectUtil.isStaticTruthy(appList)) {
        return true;
    }
    if (
        ObjectUtil.isStaticTruthy(segmentAppExclusion) &&
        _.intersection(segmentAppExclusion, appList).length === segmentAppExclusion.length
    ) {
        return false;
    }
    // eslint-disable-next-line no-magic-numbers
    return !(ObjectUtil.isStaticTruthy(segmentAppInclusion) && _.intersection(segmentAppInclusion, appList).length === 0);
};

jsonLogic.add_operation('doesUserAppInclusionOrExclusionMatches', doesUserAppInclusionOrExclusionMatches);


const apply = (rules, userAttribute) => {
    return jsonLogic.apply(rules, userAttribute);
};
```

module.exports = { apply };
__________________________________________________________________
After running I get :- 
```
{ fileName: 'config.js', data: { message: 'ACTIVE_ENV=STAGING' } }
Error: Unrecognized operation segmentAppInclusion
    at Object.jsonLogic.apply (/Users/sourav/sharechat-repos/campaign-engine-service/node_modules/json-logic-js/logic.js:368:11)
    at /Users/sourav/sharechat-repos/campaign-engine-service/node_modules/json-logic-js/logic.js:344:24
    at Array.map (<anonymous>)
    at Object.jsonLogic.apply (/Users/sourav/sharechat-repos/campaign-engine-service/node_modules/json-logic-js/logic.js:343:21)
    at /Users/sourav/sharechat-repos/campaign-engine-service/node_modules/json-logic-js/logic.js:344:24
    at Array.map (<anonymous>)
    at Object.jsonLogic.apply (/Users/sourav/sharechat-repos/campaign-engine-service/node_modules/json-logic-js/logic.js:343:21)
    at Object.jsonLogic.apply (/Users/sourav/sharechat-repos/campaign-engine-service/node_modules/json-logic-js/logic.js:258:29)
    at Object.jsonLogic.apply (/Users/sourav/sharechat-repos/campaign-engine-service/node_modules/json-logic-js/logic.js:266:29)
```
The point I am trying to make is that the custom operator is not behaving `<=`, `>=` operators where first data is extracted and compared with the second argument. Can anyone help me find a solution to this ?

**Comment by jwadhams** [comment]
I suspect the problem is that JsonLogic is really greedy about what it considers to be an "operation."

I think one way to deal with this kind of error would be to patch `jsonLogic.apply`  so if the key is not an operation, then you return it as if it was a primitive.

```javascript
-     throw new Error("Unrecognized operation " + op );
+     return logic;
```

There could plausibly be a second change where we stop using `jsonLogic.is_logic` to halt recursion, so you could have data objects (that we don't try to execute), but we still recurse **into** them to find contained JsonLogic rules that we **do** execute.
